background {
    monitor = DP-2
    path = ~/.config/hypr/hyprlock.png
}

background {
    monitor = DP-3
    path = ~/.config/hypr/hyprlock.png
}


background {
    monitor = DP-1
    path = ~/.config/hypr/hyprlock.png
}

background {
    monitor = eDP-1
    path = ~/.config/hypr/hyprlock.png
}