###################
### Desktop  ###
###################
$terminal = kitty
$fileManager = dolphin
$browser = brave-browser --enable-features=UseOzonePlatform --ozone-platform=wayland --password-store=kwallet5
$browser_alt = librewolf --enable-features=UseOzonePlatform --ozone-platform=wayland
$menu = pgrep wofi >/dev/null 2>&1 && killall wofi || wofi --show drun --conf=/etc/wofi/config --style=/etc/wofi/style.css

###################
###   Apps    ###
###################
$obsidian = $device_obsidian_path
$discord = Discord --enable-features=UseOzonePlatform --ozone-platform=wayland
$vscode = codium --enable-features=UseOzonePlatform --ozone-platform=wayland
$zed = zed
$blender = blender
$godot = $device_godot_path
$intellij_rider = rider
$intellij_rust = rustrover
$steam = steam
$winboat = winboat
$virtmachine = virt-manager


###################
###   Scripts   ###
###################
$workspaceSwitcher = $hypr_scripts/workspaces_switcher.py
$wallpaperChange = $hypr/swww/swww_randomizer.sh
