#################
### AUTOSTART ###
#################
# https://wiki.hyprland.org/Configuring/Keywords/#executing


exec-once = swww-daemon
exec-once = systemctl --user start hyprpolkitagent



# exec-once = nm-applet &
# exec-once = waybar & hyprpaper