$mainMod = SUPER # Sets "Windows" key as main modifier
$appMod = CONTROL_ALT # Sets "Windows" key as main modifier

# -----------------------------------------------------
#Applications
# -----------------------------------------------------
source = ~/.config/hypr/applications/applications.conf

# Application Binds
bind = $appMod, T, exec, $terminal
bind = $appMod, O, exec, $obsidian
bind = $appMod, E, exec, $fileManager
bind = $appMod, D, exec, $discord
bind = $appMod, B, exec, $browser
bind = $appMod, SPACE, exec, $menu

# Regular Binds
bind = $mainMod, Q, killactive,
bind = $mainMod, R, exec, $wallpaperChange