color0 #47473d
color1 #ffb4ab
color2 #ffffff
color3 #c9c7b4
color4 #ffffff
color5 #c8c9a0
color6 #c9c7b4
color7 #e5e2dd
color8 #929185
color9 #ffb4ab
color10 #ffffff
color11 #c9c7b4
color12 #ffffff
color13 #c8c9a0
color14 #c9c7b4
color15 #e5e2dd

cursor                #e5e2dd
cursor_text_color     #141311
background            #141311
foreground            #e5e2dd
selection_foreground  #c9c7ba
selection_background  #47473d
active_border_color   #ffffff
inactive_border_color #20201d
url_color             #ffffff

active_tab_foreground   #303215
active_tab_background   #ffffff
inactive_tab_foreground #c9c7ba
inactive_tab_background #20201d
cursor_trail_color      #c9c7ba
