###################
### Interfaces  ###
###################
$terminal = konsole
$fileManager = dolphin
$browser = ~/Applications/floorp/floorp

###################
###     DE      ###
###################
$menu = wofi --show drun

###################
###   Custom    ###
###################
$obsidian = ~/Applications/Obsidian/Obsidian-1.8.9.AppImage
$discord = discord


###################
###   Scripts   ###
###################
$wallpaperChange = ~/.config/hypr/swww/swww_randomizer.sh