# Monitor Layout
#####################
###  Appearance   ###
#####################
# These dont work?
# env = XCURSOR_SIZE,20
# env = HYPRCURSOR_SIZE,12

###################
###  Monitors   ###
###################

# See https://wiki.hyprland.org/Configuring/Monitors/
# hyprctl monitors all

# From Left to Right
# Drawing Pad
monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@60.00
    position = 0x2530
    scale = 1
}

# Spare Asus on Left
monitorv2 {
    output = DP-3
    mode = 1920x1080@119.98
    position = 840x610
    scale = 1
    transform = 1
}

# Main LG Monitor
monitorv2 {
    output = DP-1
    mode = 3440x1440@143.92
    position = 1920x610
    bitdepth = 10
}

# MSI Vertical Right
monitorv2 {
    output = DP-2
    mode = 2560x1440@120
    position = 5360x0
    scale = 1
    transform = 3
}





# Default
monitor = ,preferred,auto,auto
