###################
### Desktop  ###
###################
$terminal = kitty
$fileManager = dolphin
$browser = brave-browser
$browser_alt = librewolf
$menu = pgrep wofi >/dev/null 2>&1 && killall wofi || wofi --show drun --conf=/etc/wofi/config --style=/etc/wofi/style.css

###################
###   Apps    ###
###################
$obsidian = $device_obsidian_path
$discord = discord
$vscode = codium
$zed = $device_home/.local/bin/zed


###################
###   Scripts   ###
###################
$wallpaperChange = ~/.config/hypr/swww/swww_randomizer.sh
