###################
### Desktop  ###
###################
$terminal = kitty
$fileManager = dolphin
$browser = brave-browser
$browser_alt = librewolf
$menu = pgrep wofi >/dev/null 2>&1 && killall wofi || wofi --show drun --conf=/etc/wofi/config --style=/etc/wofi/style.css

###################
###   Apps    ###
###################
$obsidian = ~/Applications/Obsidian/Obsidian-1.8.9.AppImage
$discord = discord
$vscode = code


###################
###   Scripts   ###
###################
$wallpaperChange = ~/.config/hypr/swww/swww_randomizer.sh