$appMod = SUPER
$commandMod = SUPER_CONTROL
$desktopMod = SUPER_ALT

$leftMouseKey = mouse:272
$rightMouseKey = mouse:273

# -----------------------------------------------------
# Applications
# -----------------------------------------------------
source = ~/.config/hypr/applications/applications.conf

# Application Binds
bind = $appMod, T, exec, $terminal
bind = $appMod, O, exec, $obsidian
bind = $appMod, E, exec, $fileManager
bind = $appMod, D, exec, $discord
bind = $appMod, B, exec, $browser
bind = $appMod, SPACE, exec, $menu
bind = $appMod, V, exec, $vscode

# Desktop App Binds
bind = $desktopMod, N, exec, swaync-client -t
bind = $desktopMod, R, exec, $wallpaperChange

# Regular Binds
bind = $commandMod, Q, killactive,

bindm = $appMod, $leftMouseKey, movewindow
bindm = $appMod, $rightMouseKey, resizewindow