#####################
###  Appearance   ###
#####################
env = XCURSOR_SIZE,19
env = HYPRCURSOR_SIZE,12



###################
###  Monitors   ###
###################

# See https://wiki.hyprland.org/Configuring/Monitors/
# hyprctl monitors all

# Main LG Monitor
monitorv2 {
    output = DP-1
    mode = 3440x1440@143.92
    position = 0x0
    scale = 1
    # bitdepth = 10
    # cm = srgb
    supports_hdr = true
}


# MSI Vertical Right
monitorv2 {
    output = DP-2
    mode = 2560x1440@120
    position = 3440x-600
    scale = 1
    transform = 3
}

# Spare Asus on Left
monitorv2 {
    output = DP-3
    mode = 1920x1080@119.98
    position = -1920x400
    scale = 1
}

# Drawing Pad
## When on Left
monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@60.00
    position = -3840x400
    scale = 1
}

# Default
monitor = ,preferred,auto,auto