# Paths
$device_home = /home/ivan

# Plugins

# Appearance
# Do these even work?
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,12
env = HYPRCURSOR_THEME,Sweet-cursors
env = XCURSOR_THEME,Sweet-cursors

# Inputs
input {
    accel_profile = adaptive
}

cursor {
    default_monitor = DP-1
}

# Applications
$device_obsidian_path = /home/main/AppImages/obsidian.appimage
$device_godot_path = /home/main/Applications/Godot/Godot_v4.6.1-stable_mono_linux.x86_64

$phosCli = /home/main/Dev/phos-rice/phoscli/bin/phoscli

# Workspace Switcher
$workspaceMode =

workspace = 1, monitor:DP-1, default:true
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1

workspace = 5, monitor:DP-2, default:true
workspace = 6, monitor:DP-2

workspace = 7, monitor:DP-3, default:true
workspace = 8, monitor:DP-3

workspace = 9, monitor:HDMI-A-1, default:true


# Monitor Layout
# See https://wiki.hyprland.org/Configuring/Monitors/
# hyprctl monitors all
# wdisplays

# From Left to Right
# Drawing Pad
monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@60.00
    position = 0x2530
    scale = 1
    vrr = 1
}

# Spare Asus on Left
monitorv2 {
    output = DP-3
    mode = 2560x1440@120
    position = 4520x0
    scale = 1
    transform = 3
    vrr = 1
}

# Main LG Monitor
monitorv2 {
    output = DP-1
    mode = 3440x1440@143.92
    position = 1080x610
    bitdepth = 10
    vrr = 1
}

# MSI Vertical Right
monitorv2 {
    output = DP-2
    mode = 1920x1080@119.98
    position = 0x610
    scale = 1
    transform = 1
    vrr = 1
}

# Default
monitor = ,preferred,auto,auto
