# Paths
$device_home = /home/ivan

# Plugins

# Appearance
# Do these even work?
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,12
env = HYPRCURSOR_THEME,Sweet-cursors
env = XCURSOR_THEME,Sweet-cursors

# Inputs
input {
    accel_profile = adaptive
}

cursor {
    default_monitor = DP-1
}

# Applications
$device_obsidian_path = ~/Applications/Obsidian/Obsidian-1.8.9.AppImage
$device_godot_path = ~/Applications/Godot/Godot_v4.5-stable_mono_linux.x86_64
$device_winboat_path = ~/Applications/winboat/winboat-0.9.0-x86_64.AppImage

# Workspace Switcher
$workspaceMode =

workspace = name:1, monitor:DP-1, default:true
workspace = name:2, monitor:DP-1, layoutopt:direction:right
workspace = name:3, monitor:DP-1
workspace = name:4, monitor:DP-1

workspace = name:5, monitor:DP-2, default:true
workspace = name:6, monitor:DP-2

workspace = name:7, monitor:DP-3, default:true
workspace = name:8, monitor:DP-3

workspace = name:9, monitor:HDMI-A-1, default:true


# Monitor Layout
# See https://wiki.hyprland.org/Configuring/Monitors/
# hyprctl monitors all

# From Left to Right
# Drawing Pad
monitorv2 {
    output = HDMI-A-1
    mode = 1920x1080@60.00
    position = 0x2530
    scale = 1
    vrr = 1
}

# Spare Asus on Left
monitorv2 {
    output = DP-3
    mode = 1920x1080@119.98
    position = 840x610
    scale = 1
    transform = 1
    vrr = 1
}

# Main LG Monitor
monitorv2 {
    output = DP-1
    mode = 3440x1440@143.92
    position = 1920x610
    bitdepth = 10
    vrr = 1
}

# MSI Vertical Right
monitorv2 {
    output = DP-2
    mode = 2560x1440@120
    position = 5360x0
    scale = 1
    transform = 3
    vrr = 1
}

# Default
monitor = ,preferred,auto,auto
