# https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

source = ~/.config/hypr/custom_device/hyprlock.conf

general {
    hide_cursor = false
    ignore_empty_input = true
    text_trim = true
}

# Time
label {
    monitor = DP-1
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(216, 222, 233, 0.70)
    font_size = 175
    position = 0, 250
    halign = center
    valign = center
}

input-field {
    monitor = DP-1
    size = 500, 50
    outline_thickness = 5
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(30, 46, 28, 0.25)
    inner_color = rgba(190, 190, 190, 0.4)
    font_color = rgb(224, 239, 219)
    fade_on_empty = false
    placeholder_text = 
    hide_input = false
    position = 0, -400
    halign = center
    valign = center
}

# Suspend
label {
    monitor = DP-1
    text = 󰤄
    color = rgb(255, 255, 255)
    font_size = 25
    onclick = systemctl suspend
    position = -180, -30
    halign = right 
    valign = top
}

# Reboot
label {
    monitor = DP-1
    text = 󰜉
    color = rgb(255, 255, 255)
    font_size = 25
    onclick = reboot now
    position = -105, -30
    halign = right 
    valign = top
}

# Power off
label {
    monitor = DP-1
    text = 󰐥
    color = rgb(255, 255, 255)
    font_size = 25
    onclick = shutdown now
    position = -30, -30
    halign = right 
    valign = top
}

shape {
    monitor = DP-1
    size = 200,45
    rounding = 20
    border_size = 2
    border_color = rgba(255, 255, 255, 0.74)
    halign = right
    valign = top
    position = -15, -23
}
