preload = ~/Pictures/desktop/formatted/3840/ghost_in_shell_3840x2160.png
preload = ~/Pictures/desktop/formatted/1080/chrono_cross_kid_1920x1080.jpg
wallpaper = DP-1, ~/Pictures/desktop/formatted/3840/ghost_in_shell_3840x2160.png
wallpaper = DP-2, ~/Pictures/desktop/formatted/3840/ghost_in_shell_3840x2160.png
wallpaper = DP-3, ~/Pictures/desktop/formatted/3840/ghost_in_shell_3840x2160.png
wallpaper = HDMI-A-1, ~/Pictures/desktop/formatted/1080/chrono_cross_kid_1920x1080.jpg