# ######## Toolkit backends ########
env = AQ_DRM_DEVICES,/dev/dri/card0:/dev/dri/card1
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = CLUTTER_BACKEND, wayland
env = ELECTRON_OZONE_PLATFORM_HINT, auto
# env = SDL_VIDEODRIVER, wayland,windows
# # [TRIAGE] Turn this one on if games have compatibility issues
# # with Wayland
env = SDL_VIDEODRIVER, x11

# # ######## XDG specifications ########
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

# # ######## QT Variables ########
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt6ct

# https://wiki.hypr.land/Configuring/Variables/#xwayland
xwayland {
    # -- Defaults --
    enabled = true
    use_nearest_neighbor = true
    force_zero_scaling = false
    create_abstract_socket = false
}

# https://wiki.hypr.land/Configuring/Variables/#opengl
opengl {
    # Ignored since on amd gpu
    nvidia_anti_flicker = true
}

# https://wiki.hypr.land/Configuring/Variables/#render
render {
    # -- Defaults --
    direct_scanout = 0 # recommended to keep this off
    expand_undersized_textures = true
    xp_mode = false
    ctm_animation = 2
    cm_fs_passthrough = 2
    cm_enabled = true
    send_content_type = true
    cm_auto_hdr = 1
    new_render_scheduling = false
    non_shader_cm = 3
    cm_sdr_eotf = 0
}

# https://wiki.hypr.land/Configuring/Variables/#ecosystem
ecosystem {
    no_update_news = false
    no_donation_nag = true # I will donate when I can *empty wallet gif*
    enforce_permissions = false
}