
# https://wiki.hyprland.org/Configuring/Keywords/#executing

# -----------------------------------------------------
# Application Auto Start
# -----------------------------------------------------
exec-once = swww-daemon
exec-once = waybar
exec-once = GDK_BACKEND=wayland swaync


# TODO: ??
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper


# -----------------------------------------------------
# System
# -----------------------------------------------------

exec-once = systemctl --user start hyprpolkitagent

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Cursors
# exec-once = hyprctl setcursor $cursorTheme $cursorSize
# exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
# exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy
