# https://wiki.hyprland.org/Configuring/Variables/#general





# https://wiki.hyprland.org/Configuring/Dwindle-Layout/
# dwindle {
# 	preserve_split = false
# 	smart_split = true
# 	smart_resizing = true

#     pseudotile = true
# }
