# https://wiki.hyprland.org/Configuring/Variables/#general


plugin {
    hy3 {
        node_collapse_policy = 1
        autotile {
            enable = true
        }
    }
}


# https://wiki.hyprland.org/Configuring/Dwindle-Layout/
dwindle {
	preserve_split = false
	smart_split = true
	smart_resizing = true

    pseudotile = true
}
