# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    # Turn off hover focus
    follow_mouse = 2

    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1

    touchpad {
        natural_scroll = false
        disable_while_typing = false
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}