# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    numlock_by_default = true

    repeat_rate = 35
    repeat_delay = 500

    # Turn off hover focus
    follow_mouse = 2

    focus_on_close = 1
    natural_scroll = false

    # -- Device specific --
    # accel_profile

    # -- Defaults --
    kb_model =
    kb_layout = us
    kb_variant =
    kb_options =
    kb_rules =
    kb_file =

    resolve_binds_by_sym = false

    sensitivity = 0
    force_no_accel = false
    # rotation = 0
    left_handed = false
    scroll_points =
    scroll_button = 0
    scroll_button_lock = false
    scroll_factor = 1.0
    
    follow_mouse_threshold = 0
    mouse_refocus = true
    float_switch_override_focus = 1
    special_fallthrough = false
    off_window_axis_events = 1
    emulate_discrete_scroll = 1

    touchpad {
        disable_while_typing = false
        natural_scroll = false
        scroll_factor = 1.0

        middle_button_emulation = true
        tap-to-click = true
        drag_lock = 1
        tap-and-drag = true

        # -- Defaults --
        tap_button_map = # Todo: change when laptop used
        clickfinger_behavior = false
        flip_x = false
        flip_y = false
        drag_3fg = 0
    }

    touchdevice {
        # -- Defaults --
        transform = -1
        output =
        enabled = true
    }

    
    # virtualkeyboard {}
    # tablet {}
}

# https://wiki.hypr.land/Configuring/Variables/#group
group {
    auto_group = false

    groupbar {
        enabled = false
    }
    # -- Rest not used --
}


# Per device configs
# https://wiki.hypr.land/Configuring/Variables/#per-device-input-config

# -- Not used --
# https://wiki.hyprland.org/Configuring/Variables/#gestures
# https://wiki.hypr.land/Configuring/Gestures/
# gestures {}


# https://wiki.hypr.land/Configuring/Variables/#binds
binds {
    workspace_center_on = 1

    # -- Defaults --
    pass_mouse_when_bound = false
    scroll_event_delay = 300
    workspace_back_and_forth = false
    hide_special_on_workspace_change = false
    allow_workspace_cycles = false
    focus_preferred_method = 0
    ignore_group_lock = false
    movefocus_cycles_fullscreen = false
    movefocus_cycles_groupfirst = false
    disable_keybind_grabbing = false
    window_direction_monitor_fallback = true
    allow_pin_fullscreen = false
    drag_threshold = 0
}


# https://wiki.hypr.land/Configuring/Variables/#cursor
cursor {
    # Dont change this one - needed for multi monitor
    no_hardware_cursors = 1
    no_break_fs_vrr = 0 # default is 2, check if full screen games are badly affected
    min_refresh_rate = 24 # default, wont work with above disabled
    hotspot_padding = 1
    inactive_timeout = 15
    warp_on_change_workspace = 0
    
    # In custom_devices
    # default_monitor
    
    # -- Defaults --
    invisible = false
    sync_gsettings_theme = true
    no_warps = false
    persistent_warps = false
    warp_on_toggle_special = 0
    zoom_factor = 1
    zoom_rigid = false
    # zoom_detached_camera = true
    enable_hyprcursor = true
    hide_on_key_press = false
    hide_on_touch = true
    # hide_on_tablet = true
    use_cpu_buffer = 2
    warp_back_after_non_mouse_input = false
    # zoom_disable_aa = false
}
