# https://wiki.hypr.land/Configuring/Window-Rules/
# windowrule {
#   name = kitty-no-float
#   match:class = ^(kitty)$

#   float = 0
# }
# windowrulev2 = match:class ^(kitty)$, float 0

# windowrule = tile, class:^(.*)$
windowrule = tile, class:^(kitty)$
# windowrule = float, class:^(Godot_Engine)$
windowrulev2 = idleinhibit fullscreen, class:.*

windowrulev2 = tile,initialTitle:^(Godot)$,initialClass:^(Godot)$

windowrulev2 = float,title:^((.*)(DEBUG)),initialClass:^(Godot)$,initialTitle:^(.*)(DEBUG)(.*)$,class:^(Godot)$ 
# windowrulev2 = float,title:^((.*)(DEBUG))