# https://wiki.hypr.land/Configuring/Window-Rules/
# windowrule {
#   name = kitty-no-float
#   match:class = ^(kitty)$

#   float = 0
# }
# windowrulev2 = match:class ^(kitty)$, float 0

windowrule = tile, class:^(kitty)$
windowrulev2 = idleinhibit fullscreen, class:.*